version: "3"

run: when_changed

vars:
  BIN: "bin/namelist-fetch"

env:
  CGO_ENABLED: 0

tasks:
  ### run

  run:
    deps: [build]
    env:
      NLF_LISTEN_ADDR: :8765
      NLF_INTERVAL: 30s
      NLF_TARGET_FILE: ./testdir/blocked-names.txt
      NLF_TEMP_DIR: ./testdir/parts
      NLF_LIST_ADS: https://media.githubusercontent.com/media/zachlagden/Pi-hole-Optimized-Blocklists/refs/heads/main/lists/advertising.txt
      NLF_LIST_TRACK: https://media.githubusercontent.com/media/zachlagden/Pi-hole-Optimized-Blocklists/refs/heads/main/lists/tracking.txt

    cmds:
      - mkdir -p testdir{,/parts}
      - ./{{ .BIN }} {{.CLI_ARGS}}

  ### build

  build:
    sources:
      - "**/*.go"

    cmds:
      - go build -o {{ .BIN }} .

  build-all:
    sources:
      - "**/*.go"

    cmds:
      - for:
          matrix:
            OS: ['windows', 'linux', 'darwin']
            ARCH: ['amd64', 'arm64']

        cmd:
          GOOS={{ .ITEM.OS }} GOARCH={{ .ITEM.ARCH }} go build -o {{ .BIN }}-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}{{ if eq .ITEM.OS "windows" }}.exe{{ end }} .


  ### tests

  test:
    cmds:
      - go test -timeout 3m ./...
      - go tool errcheck ./...
      - go tool ineffassign ./...
