version: "3"

run: when_changed

vars:
  BIN: "bin/namelist-fetch"

env:
  CGO_ENABLED: 0

tasks:
  ### run

  run:
    deps: [build]
    cmds:
      - ./{{ .BIN }} {{.CLI_ARGS}}

  ### build

  build:
    sources:
      - "**/*.go"

    cmds:
      - go build -o {{ .BIN }} .

  build-all:
    sources:
      - "**/*.go"

    cmds:
      - for:
          matrix:
            OS: ['windows', 'linux', 'darwin']
            ARCH: ['amd64', 'arm64']

        cmd:
          GOOS={{ .ITEM.OS }} GOARCH={{ .ITEM.ARCH }} go build -o {{ .BIN }}-{{ .ITEM.OS }}-{{ .ITEM.ARCH }}{{ if eq .ITEM.OS "windows" }}.exe{{ end }} .


  ### tests

  test:
    cmds:
      - go test -timeout 3m ./...
      - go tool errcheck ./...
      - go tool ineffassign ./...
